# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MugSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('occupied', models.IntegerField(default=0)),
                ('ancestor_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mugspot.MugSpot')),
            ],
        ),
    ]
