# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mugspot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mugspot',
            name='ancestor_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mugspot.MugSpot'),
        ),
    ]
