# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugspot', '0004_mugspot_detail_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_faculty', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('friends', models.ManyToManyField(blank=True, related_name='_person_friends_+', to='mugspot.Person')),
            ],
        ),
    ]
