# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugspot', '0008_auto_20160609_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='user_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
