# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mugspot', '0010_auto_20160609_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_faculty',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
