# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('mugspot', '0012_auto_20160702_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mugspot',
            name='lat_lmt_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mugspot',
            name='lat_lmt_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mugspot',
            name='lng_lmt_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mugspot',
            name='lng_lmt_min',
            field=models.FloatField(default=0),
        ),
    ]
