# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mugspot', '0014_liveupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveupdate',
            name='pos_obj',
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='position',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
