# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mugspot', '0016_friendrequest_friendupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdate',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mugspot.MugSpot'),
        ),
    ]
